### ISSUE TITLE
L530 lights no longer work on plugin

### ISSUE THREAD

**Issue by WollfWizard** [RaresAil/homebridge-tplink-smart-light#51] opened 2023-08-30 09:00 UTC
### Describe The Bug

From last week (22 August 2023) the L530 devices stopped working entirely through the plugin. My plugin is on the latest version (v3.2.2) and the lights are on the latest firmware (1.1.0 Build 230721 Rel.224802). Can’t switch on / off the lights, change colour or dim the lights

### Expected behavior

When a request to perform an action is sent through Homebridge, the plugin should be communicating this information through to the Tapo servers to perform the action. 

### Logs

https://www.dropbox.com/scl/fi/isdot3s7uw617wvn5947b/homebridge.log.txt.xml?rlkey=hyulbwnfi6qldhft7d5cytsaz&dl=0

### Plugin Config

"addresses": [
                "192.168.1.151",
                "192.168.1.152",
                "192.168.1.153",
                "192.168.1.154",
                "192.168.1.155",
                "192.168.1.156",
                "192.168.1.157",
                "192.168.1.158",
                "192.168.1.159"
            ],
            "name": "TP-Link Tapo",
            "email": "",
            "password": "",
            "_bridge": {
                "username": "",
                "port": 51005
            },
            "platform": "HomebridgeTPLinkTapo"
        },

### Plugin Version

3.2.2

### Homebridge Version

1.6.1

### Node.js Version

16.20.2

### NPM Version

8.19.4

### Operating System

Macos

**Comment by RaresAil** [comment] 2023-08-31 08:07
Duplicate of https://github.com/RaresAil/homebridge-tp-link-tapo/issues/49

**Closed as not planned by RaresAil** 2023-08-31 08:07 UTC
