### ISSUE TITLE
Add Tapo T100 Motion Sensor Support

### ISSUE THREAD

**Issue by ELIASWGIT** [RaresAil/homebridge-tplink-smart-light#69] opened 2023-10-23 02:20 UTC
### Describe The Bug

I keep getting error messages saying that the device is unrecognised. Please if you could add in the support for the motion sensor, it would be great :)

### Expected behavior

Added Motion Sensor 

### Logs

[23/10/2023, 12:58:22] [TPLink Tapo Platform] Failed to register child accessory "Motion Sensor" of type "Unknown" (SMART.TAPOSENSOR)

### Plugin Config

{
    "bridge": {
        "name": "Homebridge 547C",
        "username": "0E:1A:5E:16:54:7C",
        "port": 51302,
        "pin": "354-64-223",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "deep-purple",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "cameras": [
                {
                    "name": "Camera",
                    "ipAddress": "192.168.1.136",
                    "password": "",
                    "streamUser": "",
                    "streamPassword": ""
                }
            ],
            "platform": "tapo-camera"
        },
        {
            "addresses": [
                "192.168.1.100",
                "192.168.1.102",
                "192.168.1.117"
            ],
            "name": "TPLink Tapo Platform",
            "email": "",
            "password": "",
            "platform": "HomebridgeTPLinkTapo"
        },
        {
            "devices": [
                {
                    "name": "Mi Air Purifier 2H",
                    "ip": "192.168.1.101",
                    "token": "",
                    "deviceId": "",
                    "model": "zhimi.airpurifier.mc2",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "",
                        "password": "",
                        "country": "sg"
                    },
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                },
                {
                    "name": "Mi Wi-Fi Range Extender Pro",
                    "ip": "192.168.1.111",
                    "token": "",
                    "deviceId": "",
                    "model": "xiaomi.repeater.v3",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "",
                        "password": "",
                        "country": "sg"
                    },
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                }
            ],
            "platform": "miot"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "",
                "password": "",
                "countryCode": "61",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
    ],
    "disabledPlugins": [
        "homebridge-camera-ui"
    ]
}

### Plugin Version

Latest

### Homebridge Version

Latest

### Node.js Version

Latest

### NPM Version

Latest

### Operating System

Latest

**Comment by RaresAil** [comment] 2023-10-23 04:23
Hey, you can join discord to help me with this, also i will close this one because is a duplicate of  another issue created #55

**Closed as not planned** 2023-10-23 04:23 UTC

**Comment by ELIASWGIT** [comment] 2023-10-23 04:26
All good but how do I join you on discord? Is there a link?
