### ISSUE TITLE
Light bulbs getting removed when power loss

### ISSUE THREAD

**Issue by Johnny99211** [RaresAil/homebridge-tplink-smart-light#24] opened 2022-10-19 16:22 UTC
### Describe The Bug

Last week I had a power loss for hours. Because of this, all my Tapo lightbulbs were removed from Homebridge and also from HomeKit. This is bad since I configured a lot of stuff. Instead, it should be marked as unreachable and not removed...

### Expected behavior

-

### Logs

-

### Plugin Config

-

### Plugin Version

-

### Homebridge Version

-

### Node.js Version

-

### NPM Version

-

### Operating System

-

**Comment by RaresAil** [comment] 2022-11-25 18:27
Hello, sorry for the inconvenience and slow response time, in the next version of the app i will make the fix for this

**Comment by Johnny99211** [comment] 2022-12-09 16:13
Hi, any new update on re-connection when the bulb get's online again after disconnect?

**Comment by energiumOn** [comment] 2022-12-30 14:05
Hi, I have the same issue with a number of tapo bulbs. I have to remove accessory cache from Homebridge and reconfigure on Homekit every time. It’s becoming very annoying. I hope time allows for a sooner update 🤗.

**Comment by RaresAil** [comment] 2023-01-04 09:35
Hey, i was away for some time, i will work on fixing this and releasing it this week 😃

**Closed as completed** 2023-01-06 11:46 UTC
Labels: bug

**Comment by RaresAil** [comment] 2023-01-06 11:52
The issue is fixed in version 3.2.2
